// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlnbkdpaawcpayjmmtyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbmJrZHBhYXdjcGF5am1tdHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTQ5NTksImV4cCI6MjA2OTQzMDk1OX0.GIx6af1OfiRX9iGyLnGJ5coIf47ruR2P1Iqec0NCrrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});